image: docker:19.03.0

variables:
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.0-dind

# lint requires a lot of packages to be _compiled_
#  - burns a lot of CPU minutes on the shared runners.
#  - lint
stages:
  - build
# publish updates to web site
#  - publish

cache:
  key: "$CI_BUILD_REF"

before_script:
#  - env | sort
  - apk update
  - apk upgrade
  - apk add --no-cache python3 py3-pip build-base freetype-dev gcc libffi-dev make musl-dev 
  - pip3 install peewee pytest pytest-benchmark numpy
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - ls -l

#lint:
#  stage: lint
#  script:
#    - apk update
#    - apk upgrade
#    - apk add --no-cache build-base freetype-dev gcc make musl-dev python3 python3-dev py3-pip
#    - pip3 install pylint
#    - pip3 install --requirement requirements.txt
#    - scripts/lint.sh    -p ${CI_PROJECT_NAMESPACE} -r ${CI_REGISTRY}

build:
  stage: build
  script:
    - scripts/test.sh    -p ${CI_PROJECT_NAMESPACE} -r ${CI_REGISTRY}
    - scripts/build.sh   -p ${CI_PROJECT_NAMESPACE} -r ${CI_REGISTRY}
    - scripts/tag.sh     -p ${CI_PROJECT_NAMESPACE} -r ${CI_REGISTRY}
    - scripts/push.sh    -p ${CI_PROJECT_NAMESPACE} -r ${CI_REGISTRY}

